import type { Metadata } from "next";
import { Geist, Geist_Mono, Mochiy_Pop_P_One, M_PLUS_1 } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import AnnouncementBar from "./components/AnnouncementBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const mochiyPop = Mochiy_Pop_P_One({
  variable: "--font-mochiy-pop",
  subsets: ["latin"],
  weight: "400",
});

const mPlus1 = M_PLUS_1({
  variable: "--font-m-plus-1",
  subsets: ["latin"],
  weight: "400", // choose 400 or 700 as needed
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mochiyPop.variable} ${mPlus1.variable} antialiased`}
      >
        <AnnouncementBar />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
